function [sol,exitflag] = Trap2DTraj(N,BC,param)
%TRAP2DTRAJ Summary of this function goes here
%   Detailed explanation goes here

DV0 = init_guess(N,param,BC);
% [c0, ceq0] = nonlcon_trap(DV0, N, param, BC);

if ~param.show_solver
    options = optimoptions('fmincon',...
      'Algorithm','sqp', ...
      'MaxFunctionEvaluations',1e6, ...
      'MaxIterations',2e4, ...
      'Display','off', ...
      'FiniteDifferenceType','central');
else
    options = optimoptions('fmincon',...
      'Algorithm','sqp', ...
      'MaxFunctionEvaluations',1e6, ...
      'MaxIterations',2e4, ...
      'Display','iter', ...
      'FiniteDifferenceType','central');
end
[sol,~,exitflag,~] = fmincon(@(DV) objectiveFunc(DV,N),DV0, [], [], [], [], [], [], ...
                       @(DV)nonlcon_trap(DV,N,param,BC), options);



end

